### ISSUE TITLE
REquires "Hide overlay when game is unfocussed" to be disabled

### ISSUE THREAD

**Issue by ChrisVenus** [Haato3o/DecorationSearch#1]
When using this plugin with the "Hide overlay when game is unfocussed" it seems to get confused when I try to use the decoration search. The box appears when I open the decoration selection but keyboard input is still with the game. If I click the search window then it seems to disappear and reappear and still not have focus. I assume what is happening is that when I click on it it gets focus, because the game is unfocussed it then hides the overlay which now it is gone leaves the game focussed so it comes back again.

Ideal fix would be to make sure the search window doesn't hide itself if it has focus, even with the above option on. I guess next best would just be a warning that the above option needs to be off and to not show the window at all if it is on.

**Comment by haato3o** [comment]
Fixed in https://github.com/Haato3o/DecorationSearch/commit/0cbdd4be18cf9674e7be1bdfac0292d8e88da104 (v1.0.2.0)
